### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by AxelTerizaki** [Zazama/node-id3#39]
Currently the module is using callbacks, but I wanted it to use promises as I'm writing my app with ES6.

I wrote a little test like that : 

```JS
import id3 from 'node-id3';
import {promisify} from 'util';

const file1 = '../img.mp3';
const file2 = '../noimg.mp3';

export function readID3(file) {
    return promisify(id3.read)(file);
}


async function main() {    
    try {
        const tags1 = await readID3(file1);
        const tags2 = await readID3(file2);
        console.log(tags1);
        console.log(tags2);
    } catch (err) {
        console.log(err);
    }
}

main().then(() => {
    process.exit();    
});
```

However, this fails with : 

```
D:\perso\toyundamugen-app\node_modules\node-id3\index.js:234
                    let tags = this.getTagsFromBuffer(data, options)
                                    ^

TypeError: this.getTagsFromBuffer is not a function
    at D:\perso\toyundamugen-app\node_modules\node-id3\index.js:234:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
```

I had a friend look into it and he had to create its own promisify function. This allows to promisify your module :

```JS
export function readID3(fileBuffer, options) {
  return new Promise(
      (resolve, reject) =>
          id3.read(
                fileBuffer,
              options,
              (err, tags) => {
                  if (err) {
                      reject(err);
                  } else {
                      resolve(tags);
                  }
              }
          )
  )
}
```

However this is not really satisfying. The best thing IMHO would be that node-id3 natively supports promises.

This is due to a binding problem with `this`.

I'd be grateful if you could look into this.

**Comment by Zazama** [comment]
Your code is working for me using the following bind inside the promisify function.
`util.promisify(id3.read.bind(id3))`

**Comment by AxelTerizaki** [comment]
Indeed, that's simpler and more elegant. Thank you ^^
