### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE]: The value "4191390185" is invalid for option "size"

### ISSUE THREAD

**Issue by freakysmurf** [Zazama/node-id3#54]
```
buffer.js:269
    throw err;
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "4191390185" is invalid for option "size"
    at Function.alloc (buffer.js:278:3)
    at new Buffer (buffer.js:180:19)
    at NodeID3.getTagsFromBuffer (C:\test\nodejs\node_modules\node-id3\index.js:328:31)
    at NodeID3.read (C:\test\nodejs\node_modules\node-id3\index.js:226:25)
    at NodeID3.update (C:\test\nodejs\node_modules\node-id3\index.js:269:32)
```

Test code:
```
var nodeID3 = require('node-id3');
    
let path = 'giuseppe-tomasi-di-lampedusa-der-leopard-1-4.mp3';
let tags = {
    title: 'Giuseppe Tomasi di Lampedusa: Der Leopard (1/4)',
    album: 'BR 2 | radioTexte'							
};

let success = nodeID3.update(tags, path);
```

[giuseppe-tomasi-di-lampedusa-der-leopard-1-4.mp3](https://cdn-storage.br.de/iLCpbHJGNL9zu6i6NL97bmWH_-bd/_-QS/_Akc9-8f571S/190905_2105_radioTexte_Giuseppe-Tomasi-di-Lampedusa-Der-Leopard-14.mp3?download=true)

**Comment by RoyceTheBiker** [comment]
I am getting the same error when attempting to read the file. It crashes on the NodeID3.read.

```
NodeID3.read(file, function(err, tags) {
	console.log('got a tag');
 });
```

```
buffer.js:269
    throw err;
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "3116570010" is invalid for option "size"
    at Function.alloc (buffer.js:278:3)
    at NodeID3.getTagsFromBuffer (/mnt/hgfs/Development/GitLab.BigHouse/SiliconTao-open-source/JukeBox/backend/node_modules/node-id3/index.js:367:38)
    at NodeID3.<anonymous> (/mnt/hgfs/Development/GitLab.BigHouse/SiliconTao-open-source/JukeBox/backend/node_modules/node-id3/index.js:241:37)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by SharkAttack86** [comment]
Same error here. It seems related to some specific files. In my case, i got it in 1 file of like 50.000

```
buffer.js:324
    throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "3083731024" is invalid for option "size"
    at Function.alloc (buffer.js:333:3)


    at NodeID3.getTagsFromBuffer (/home/daniele/node_modules/node-id3/index.js:367:38)
    at NodeID3.<anonymous> (/home/daniele/node_modules/node-id3/index.js:241:37)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by Zazama** [comment]
Can you upload an affected mp3 or send it per mail to jan.metzger@gmx.net? 
The link in the first post is offline, sadly.

**Comment by SharkAttack86** [comment]
@Zazama sure. I sent you an email with that mp3 file.

**Comment by Zazama** [comment]
@SharkAttack86 Thank you, the problem with your file was due to the usage of an older version (ID3v2.2.0) that was not supported by node-id3. I've added basic read support (text frames + picture) and published a new version.

@RoyceTheBiker @freakysmurf There's a possibility that your issue is a different one with the same outcome (alloc overflowing), would you mind sending me your failing mp3? In the meantime, I've added a workaround so that alloc is not called if it would overflow. If there's a different issue with your mp3, the tags after the failing one would just not get read.

**Comment by SharkAttack86** [comment]
@Zazama Thank you. It works wonderfully with that one
