### ISSUE TITLE
Crashes Node with Buffer Out of Bounds

### ISSUE THREAD

**Issue by ev5unleash** [Zazama/node-id3#59]
Found a bug where reading certain tags can cause node-id3 to crash the whole app (even in a try catch). 

internal/buffer.js:75
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt32BE (internal/buffer.js:300:5)
    at NodeID3.readPopularimeterFrame (node_modules\node-id3\index.js:1078:38)
    at NodeID3.<anonymous> (node_modules\node-id3\index.js:465:64)
    at Array.map (<anonymous>)
    at NodeID3.<anonymous> (node_modules\node-id3\index.js:463:40)
    at Array.forEach (<anonymous>)
    at NodeID3.getTagsFromBuffer (node_modules\node-id3\index.js:437:12)
    at NodeID3.<anonymous> (node_modules\node-id3\index.js:292:37)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

Even if the package failed to read the file properly, could we add some safety for the failure instead of just killing the app?

**Comment by Zazama** [comment]
fixed in https://github.com/Zazama/node-id3/commit/f354025ecad7946368cf1de600f78f7163ce2847

published in 0.1.14
