### ISSUE TITLE
Read-only files returns success flag

### ISSUE THREAD

**Issue by cafeinlove** [Zazama/node-id3#71]
Just discovered this library and fully enjoying it!

I have issue with read-only files though: they stay unchanged as they're not meant to be, but they still returns success flag when I try to `update()` it.

Below is my implementation.

```
updateTags() {
  // generate metadata for this track
  const tags = this.getTags();
  // file path
  const file = this.path;
  // assign new data
  // *note*: returns true when the file is read-only
  const success = NodeID3.update(tags, file);

  if (success) {
    logger.info(`Updated: ${file}`);
  } else {
    logger.error(`Failed to update: ${file}`);
  }
}
```

**Comment by Zazama** [comment]
Interesting, I'm getting an error when trying to write or update a read-only file on Windows.

```
C:\Users\janzz\Desktop\node-id3>node example/test.js
Error: EPERM: operation not permitted, open './example/test.mp3'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at NodeID3.write (C:\Users\janzz\Desktop\node-id3\index.js:299:16)
    at NodeID3.update (C:\Users\janzz\Desktop\node-id3\index.js:471:21)
    at Object.<anonymous> (C:\Users\janzz\Desktop\node-id3\example\test.js:52:23)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: './example/test.mp3'
}
```

Can you give me some information about your OS and how you set that file read-only?

**Comment by cafeinlove** [comment]
Sure, forgot to include that.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

The sound file that I've downloaded on the web was already set read-only. I just tried to reproduce the issue by taking a random mp3 file from my song library, open with Windows file explorer -> properties menu -> general tab -> tick read-only and run the `NodeID3.update()` method on the file - it still returned me true

**Comment by cafeinlove** [comment]
Omg didn't think about that! Just confirmed that the returned value was an error object, and fixed my code like below. Thanks for your explanation.

```
updateTags() {
  const tags = this.formatTags();
  const file = this.path;
  const response = NodeID3.update(tags, file);

  if (response instanceof Error) {
    return logger.error(response.message);
  }
  logger.info(`Updated: ${file}`);
}
```

**Comment by Zazama** [comment]
Great, I'm gonna close this issue & change the README later, if you have another problem/question, feel free to open a new one.
